name: flutter_template
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  after_layout: ^1.1.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  fluro: ^2.0.3
  flutter_bloc: ^7.2.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  json_annotation: ^4.3.0
  kiwi: ^4.0.1
  lint: ^1.0.0
  logging: ^1.0.2
  retrofit: ^2.0.1
  shared_preferences: ^2.0.7
  velocity_x: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.1
  retrofit_generator:

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
